name: Build

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm ci --omit=optional --prefer-offline --no-audit

      - name: Build
        run: npm run build
